[models]

[models.text]
path = "/home/websinthe/aigen/textgen/text_checkpoints"
models = [
"dolphin-2.2-yi-34b-200k.Q6_K.gguf",
"dolphin-2.9.3-mistral-nemo-12b.Q8_0.gguf",
"L3.1-MOE-4X8B-Dark-Reasoning-Super-Nova-RP-Hermes-R1-Uncensored-25B.Q8_0.gguf",
"MS-24B-Bathory.Q8_0.gguf",
"OLMo-2-0325-32B.Q6_K.gguf",
"oxy-1-small-Q6_K.gguf",
"Qwen3-Coder-30B-A3B-Instruct-UD-Q6_K_XL.gguf",
"QWQ-RPMax-Planet-32B-ablated.Q6_K.gguf",
"SmolLM3-f16.gguf",
"SmolLM3-Q4_K_M.gguf",
"SmolLM3-Q8_0.gguf",
"venice_q6.gguf",
]

