[project]
name = "agentic-plot-mvp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "requests>=2.32.5",
    "setuptools>=80.9.0",
    "smolagents[toolkit]>=1.22.0",
    "wheel>=0.45.1",
]
